### ISSUE TITLE
Release numpy from requirements.txt

### ISSUE THREAD

**Issue by volcan01010** [volcan01010/bng#5]
### Acceptance criteria

+ [ ] `numpy` is removed from requirements.txt. It is no longer needed.

**Comment by iamnandhu** [comment]
Just to make it clear .. do you want to remove `numpy` entirely?

**Comment by volcan01010** [comment]
Yes, please.  The first version of bng used numpy to get the `floor` function, but now I get that from `math` in the standard library.

It's a one-line fix, so a very easy good first issue.  Thank you for being interested.

**Comment by volcan01010** [comment]
Closed by #7
